### ISSUE TITLE
Doesn't seem to work on the new Xcode version (7.3)

### ISSUE THREAD

**Issue by Maslor** [zats/AdjustFontSize-Xcode-Plugin#32] opened 2016-04-08 13:25 UTC

**Comment by xhonato** [comment] 2016-04-09 17:05
Hello i have the same problem. It doesnt work on xcode 7.3 version.

**Comment by zats** [comment] 2016-04-10 01:19
Is it possible that it is related to the change of the recent hotkeys change? I did it to avoid conflict with interface builder hotkeys that several people complained about

**Comment by xhonato** [comment] 2016-04-10 07:15
@zats Hello. I dont know but what i see when i go to View-Font Size is in this picture: 

<img width="553" alt="screen shot 2016-04-10 at 10 14 00" src="https://cloud.githubusercontent.com/assets/14541825/14408623/17dc3162-ff05-11e5-8a67-73de6ed6a3f8.png">

**Comment by Maslor** [comment] 2016-04-10 15:54
My font enlarge (`ctrl & +`) is working but `ctrl & -` is not.

**Comment by dmcrodrigues** [comment] 2016-04-14 09:54
`CTRL & -` does not work when the code editor has the focus, it seems that this mapping is used for something in the `Navigate` menu. If you select something in the _Project Navigator_, moving out the focus of the code editor, it works as expected.

@zats we probably should use another mapping.

**Comment by zats** [comment] 2016-04-14 17:39
I'll try to take a look at it this weekend, thanks a lot for the insight!!

**Comment by nikitavoloboev** [comment] 2016-07-09 20:58
I can't seem to download AdjustFonts with Alcatrez package manager as it just doesn't allow it. Is there any way that I can make it work with Xcode 7.3?

Thank you for any help.

**Comment by zats** [comment] 2016-07-10 14:20
Have you tried downloading the project itself and building it with Xcode?

**Comment by nikitavoloboev** [comment] 2016-07-10 19:16
I have. However when you run it, it works but when you quit the adjustfontsize Xcode project, it stops working and I don't know why.

**Comment by zats** [comment] 2016-07-11 01:34
I just tried to install the plugin from scratch in 7.3.1 through Alcatraz and it works fine for me. Any chance you can try to reinstall it while having the Console.app open - it might output some sort of warnings in there. Sorry I can't find a better solution yet

**Comment by nikitavoloboev** [comment] 2016-07-15 20:48
It seems to be working now, thank you.

However there is one issue I found. When using swift playgrounds, when you zoom in and out, you can no longer see the values on the right : 

![2016-07-15 at 22 47](https://cloud.githubusercontent.com/assets/6391776/16888100/2c3cd394-4ade-11e6-9526-f3e75b727d8b.png)

Perhaps you can try and see if you can replicate it. Thank you a lot and I hope something like this can be fixed.

**Comment by zats** [comment] 2016-07-15 20:51
I actually use playground extensively and it seems to work for me 
There is another issue with playground though - sometimes they'd get stuck evaluating my code and not showing anything.
If you're adding a `print("Hello")` is getting printed in the console? (`⌘⇧Y`)

P.S. are you aware that plugins are going away from Xcode 8? Apple sealed Xcode so it won't side load any bundles - all plugins rely on this to run

**Comment by nikitavoloboev** [comment] 2016-07-15 21:01
I have just tried writing the 'print("Hello") line in Xcode and it does not show it on the side either. It's very strange, I am sure the issue is with this plugin as it only stops working after I try and adjust the font size with it.

I have heard about Xcode stopping the side loading of plugins. I also think they are introducing something like Xcode extensions to the app, isn't it the same thing as plugins?

**Comment by zats** [comment] 2016-07-15 21:03
I can only suggest to re-run playground with plugins disabled
New plugins API is very limited and doesn’t allow to play with interface -
only with the text of the editor, hence this plugin and many others will be
retired until Apple re-introduce compatible API

**Comment by nikitavoloboev** [comment] 2016-07-15 21:08
So if I was to try and use the beta now, there would be no way to increase / decrease font size with a hotkey? Such functionality should really be part of the default capabilities. This is really strange that you need a plugin for that. :(

**Comment by ghost** [comment] 2016-08-10 22:26
I'm using Xcode 7.2 and `ctrl & -` is actually increasing the font, but no possibility to decrease it. Is it normal ?

**Comment by zats** [comment] 2016-08-10 23:00
no, it is definitely not normal, can you please take a screenshot of your "Font Size" menu (Under "View" menu) so I can see the hotkeys binding

**Comment by ghost** [comment] 2016-08-11 10:25
Here it is : 

![capture d ecran 2016-08-11 a 12 23 27](https://cloud.githubusercontent.com/assets/9343129/17585875/9a878688-5fbe-11e6-8861-725d0e0fa496.jpg)

**Comment by zats** [comment] 2016-08-11 15:03
That's odd, according to the screenshot `⌃-` should decrease font size, not increase it
please try the steps described in readme to remap the hotkeys and open a new issue if it still doesn't work - this issue became catch-all, I'll close it 🙂

**Closed by zats** 2016-08-11 15:03 UTC
